### ISSUE TITLE
Cassandra 3.0.17 cannot start with agent

### ISSUE THREAD

**Issue by serban21** [instaclustr/cassandra-exporter#29]
I tried to test it with Cassandra 3.0.17 running as an agent. It seems it hangs in CassandraDaemon.java, before being able to open log files, so there is no debug info. Killing the process will create a new Java/Cassandra process, which seems to be working (both Cassandra and the agent).

I'm using Java 1.8.0_102 on Amazon Linux 2017.09.

**Comment by podile** [comment]
Same thing happening for me. Can someone help out?

**Comment by serban21** [comment]
@podile I tested it again with the latest version (0.9.8) and the problem seems to be fixed by #30 

As far as I'm concerned this can be closed

**Comment by podile** [comment]
@serban21 Thanks for the update, I will check with the latest version (0.9.8).

**Comment by zegelin** [comment]
Closing, as #30 fixes this.
