### ISSUE TITLE
Provide a mean to reproduce benchmarks results

### ISSUE THREAD

**Issue by erebe** [instaclustr/cassandra-exporter#3]
Hello,

I am the author of criteo/cassandra_exporter and I would like to be able to reproduce your benchmarks in order to understand where are coming from the differences in performance from the other exporters you compare.

On my side, even on a pretty loaded cluster with a lot of keyspaces/tables the scraping time does not take more than 9sec (the machines have big cpus). But even while, when I switched from jmx_exporter, I haven't noticed a huge performance drop regarding the scrapping time. So I am a bit concerned on how you end-up with those results.

Can you please provide a mean to reproduce your benchmarks and the config you are running them on ?

Thanks in advance :)

**Comment by erebe** [comment]
Hi,
Thanks for the quick reply :)
I will look into that later in the week and will keep you posted.

As a side note, while performance is nice, you should warn/advertise the downside of running the exporter as an agent, most notably:
- You have to restart your cluster if you want to upgrade the exporter plugin (may not be an issue if you are on kubernetes)
- You are sharing the same jvm/heap than cassandra itself, so requesting too frequently the endpoint may result in triggering GC that will cause Cassandra to pause

Also if you want to improve further your performance, you can look to add gzip support for you http server, it make a big difference.
https://github.com/prometheus/client_java/blob/master/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java#L71

**Comment by erebe** [comment]
Hi back,

So indeed my exporter was way slower with a lot of tables.

**Comment by zegelin** [comment]
Thanks for the suggestions of notes/warnings about running an exporter as an agent. I'll consider adding them to the README.

> Also if you want to improve further your performance, you can look to add gzip support for you http server, it make a big difference.

GZip and Deflate is already supported -- Netty's `HttpContentCompressor` is part of the pipeline.

For example, the following request returns GZip encoded content which is successfully decompressed with `gunzip`:

```
curl -H "Accept-Encoding: gzip" localhost:29600/metrics | gunzip
```

> ... are my calls to mbean.getAttributes in order for the exporter to be able to not export them.

Yes, `getAttributes` is one of the slowest JMX calls in my experience.

**Comment by erebe** [comment]
Ok for gzip, I should have missed it :)
Good luck
