### ISSUE TITLE
Missing Client Reads/Writes metrics ?

### ISSUE THREAD

**Issue by ahmedjami** [instaclustr/cassandra-exporter#32]
Hi,
Can you tell me where I can find the metric which returns the client read count (per table) please ?

Thanks.

**Comment by ahmedjami** [comment]
I see this in the doc:

sum(cassandra_table_operation_latency_seconds_count) by (keyspace, operation) # total operations by keyspace & type

But "_count" is not the count of observe for a summary metric ?

**Comment by zegelin** [comment]
Hi @ahmedjami.

Correct, `cassandra_table_operation_latency_seconds_count` is the correct metric to use. The latency histograms are updated on every read & write operation, and hence the sum of `_count` metric across all `operation` labels represents the total number of reads & writes for a table.

You can aggregate further depending on the `by` clause you use…

The following will give you the total reads & writes across the cluster:
`sum(cassandra_table_operation_latency_seconds_count)`

or, totals every table cluster-wide:
`sum(cassandra_table_operation_latency_seconds_count) by (table)` 

or, total reads & writes per node:
`sum(cassandra_table_operation_latency_seconds_count) by (cassandra_node)`

or, totals for each table, for each node:
`sum(cassandra_table_operation_latency_seconds_count) by (cassandra_node, table)`

You can also get the count for just reads or writes, by specifying a value for the `operation` label, i.e.:
`sum(cassandra_table_operation_latency_seconds_count{operation=~"read|range_read") by (cassandra_node, table)`

`operation` is on of: `read`, `range_read` or `write`.

Slightly poor naming I agree. We plan to write better documentation at some point :)
