### ISSUE TITLE
Using --exclude

### ISSUE THREAD

**Issue by podile** [instaclustr/cassandra-exporter#66]
I am using file to specify the main arguments, and using another file to exclude metrics families. However, the the metrics supposed to be excluded still appearing in  /metrics. Can you please go through the below configuration and check if there are any issues?

Version: V0.9.10

`JVM_OPTS="$JVM_OPTS -javaagent:$CASSANDRA_HOME/lib/cassandra-exporter-agent.jar=@$CASSANDRA_HOME/conf/metrics-exporter.properties"`

I made sure the config files are exist. 

metrics-exporter.properties

```
--listen=*****************
--global-labels=CLUSTER,NODE,DATACENTER
--exclude-system-tables
--no-table-labels
--exclude=@/opt/nosql/clusters/cassandra-3004/conf/exclude-metrics.properties
```

exclude-metrics.properties

```
cassandra_buffer_pool_misses_total
cassandra_buffer_pool_size_bytes
cassandra_cache_capacity_bytes
cassandra_cache_entries
cassandra_cache_estimated_size_bytes
cassandra_cache_hits_total
cassandra_cache_miss_latency_seconds
cassandra_cache_requests_total
cassandra_client_authentication_successes_total
cassandra_commit_log_commit_latency_seconds
cassandra_commit_log_completed_tasks_total
```

Metrics pull Response contains excluded metrics
```
# HELP cassandra_buffer_pool_misses_total Total number of requests to the BufferPool requiring allocation of a new ByteBuffer.
# TYPE cassandra_buffer_pool_misses_total counter
cassandra_buffer_pool_misses_total{cassandra_cluster="GLDPS_CAAS_UAT",cassandra_node="147.107.191.84",cassandra_datacenter="CST"} 0.0 1582203227803
```

**Comment by zegelin** [comment]
Thanks for the bug report @podile.

The config looks correct from first glance. I'll see if I can reproduce locally.

**Comment by zegelin** [comment]
@podile, using the config that you've provided I'm able to reproduce the issue. I'll investigate the cause.
