### ISSUE TITLE
Add Grafana templates

### ISSUE THREAD

**Issue by zegelin** [instaclustr/cassandra-exporter#8]
These should be some example Grafana templates that show off the exporter.

+ add some screenshots to the README.

**Comment by yanniszark** [comment]
First of all, thanks for the great effort on this exporter, I have tried it and it works like a charm!
Is there a plan to release a Grafana dashboard or adapt an existing one for this exporter?

The issue with Cassandra not natively exporting metrics to Prometheus, is that every exporter names metrics a little different, so dashboards are not portable.
I have tried the following dashboards and failed:
* https://grafana.com/dashboards/5408
* https://grafana.com/dashboards/6258

I would like very much to use cassandra-exporter, however I am not a Grafana expert and I didn't find an easy way to make existing dashboards work.

**Comment by Louies89** [comment]
@zegelin @yanniszark got any dashboard?

**Comment by b1ackbeardast** [comment]
I would also like to see a dashboard for this exporter.

**Comment by BrianGallew** [comment]
I'll be contributing one shortly if I can ever get the internal reviews completed.

**Comment by danischroeter** [comment]
@BrianGallew Hi Brian. Did you have any luck with your reviews?
I (and I guess anybody else) would be happy for any dashboard even if incomplete ;) that would greatly reduce the ramp up time to start monitoring. And maybe we can then even help to improve your board as well ;)
Thx.

**Comment by BrianGallew** [comment]
Not yet.  In truth, I've been busy with other stuff.  I'm on vacation right
now, but I'll try to get it out in a couple weeks.

**Comment by danischroeter** [comment]
thx a lot @zegelin !
