### ISSUE TITLE
prometheus-exclusions

### ISSUE THREAD

**Issue by universalle** [instaclustr/cassandra-exporter#85]
How prometheus-exclusions file should look like?
Real examples?

How to exclude for example these metrics?

cassandra_dropped_messages_cross_node_latency_seconds
cassandra_dropped_messages_internal_latency_seconds
cassandra_dropped_messages_total

**Comment by hadarizi** [comment]
Hi @universalle 
under cassandra-env.sh add:
JVM_OPTS="$JVM_OPTS -javaagent:<path>/cassandra/lib/cassandra-exporter-agent-0.9.11.jar=@<path>/cassandra/conf/metrics-exporter.yml"

under metrics-exporter.yml:
--global-labels=CLUSTER,NODE
--exclude-keyspaces=dse_security
**--exclude=@<path>/cassandra/conf/exclude-metrics.properties**

under exclude-metrics.properties define the metrics to exclude:
cassandra_dropped_messages_cross_node_latency_seconds
cassandra_dropped_messages_internal_latency_seconds
cassandra_dropped_messages_total

Don't forget to set the right permissions to those files.
GL

**Comment by universalle** [comment]
Thank you very much @hadarizi
